# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: validate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '7' # The .NET SDK version to use
  DOTNET_SLN: './Source/Libation.sln'
  DOTNET_CONFIGURATION: 'Release'

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yml