# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish

on:
  push:
    tags:
      - 'v*'

env:
  DOTNET_VERSION: '7' # The .NET SDK version to use
  DOTNET_SOURCE: './Source'
  DOTNET_CONFIGURATION: 'Release'

jobs:
  build:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      version: ${{ github.ref_name }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Libation ${{ github.ref }}
          body: <Put a body here>
          draft: true
          prerelease: false
      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ./artifacts