# validate.yml
# Validates that Libation will build on a pull request or push to master. 
---
name: validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/build.yml
